class Data:

 data = [['top', 't-shirt', ['dark', 'bright'], ['casual', 'sportswear'], 0.0],
        ['top','blouse', ['bright'], ['business', 'evening'], 200.0],
        ['top','bodysuit', ['dark'], ['casual', 'evening'], 150.0],
        ['top','sleeveless', ['dark'], ['casual'], 110.0],
        ['top','tank', ['bright'], ['casual', 'sportswear'], 70.0],
        ['top','sweater', ['dark'], ['casual', 'business'], 200.0],
        ['top','vest', ['dark'], ['business'], 300.0],
        ['top','blazer', ['dark'], ['business'], 430.0],
        ['top','jacket', ['bright'], ['casual'], 0.0],
        ['top','hoodie', ['bright', 'dark'], ['sportswear'], 230.0],
        ['top','cardigan', ['bright'], ['casual'], 300.0],
        ['bottom','jeans', ['dark'], ['casual'], 150.0],
        ['bottom','knee length pant', ['bright'], ['casual'], 220.0],
        ['bottom','ankle length pant', ['dark'], ['business'], 0.0],
        ['bottom','high waist pant', ['bright'], ['business'], 150.0],
        ['bottom','legging', ['dark'], ['casual'], 100.0],
        ['bottom','sweatpants', ['bright'], ['casual'], 100.0],
        ['bottom','wide leg pants', ['dark', 'bright'], ['business', 'evening'], 500.0],
        ['bottom','maxi skirt', ['bright'], ['evening'], 500.0],
        ['bottom','midi skirt', ['dark'], ['business'], 0.0],
        ['bottom','short skirt', ['bright'], ['casual'], 400.0],
        ['shoes','sandals', ['dark'], ['casual', 'evening'], 120.0],
        ['shoes','sneakers', ['bright'], ['sportswear', 'casual'], 300.0],
        ['shoes','high heel', ['dark'], ['evening'], 0.0],
        ['shoes','mid heel', ['bright'], ['casual', 'business'], 400.0],
        ['shoes','low heel', ['dark'], ['business'], 150.0],
        ['shoes','flat', ['bright'], ['casual'], 0.0],
        ['shoes','boots', ['dark'], ['casual'], 500.0],
        ['neck','necklace', ['dark'], ['business', 'evening'], 150.0],
        ['neck','choker', ['bright'], ['sportswear', 'casual'], 0.0],
        ['neck','scarf', ['bright'], ['casual', 'evening'], 250.0],
        ['neck','tie', ['dark'], ['business'], 100.0],
        ['neck','bow tie', ['dark'], ['business', 'evening'], 100.0],
        ['handbag','backpack', ['bright'], ['sportswear'], 100.0],
        ['handbag','purse', ['bright'], ['business'], 600.0],
        ['handbag','clutch', ['dark'], ['evening'], 500.0],
        ['handbag','belt bag', ['dark'], ['casual'], 300.0],
        ['handbag','cross bag', ['dark'], ['business'], 0.0]]


